$(document).ready(function(){
    $("nav").hide();
    $(".cerrar-menu").hide();
    $(".btn-menu").click(function(){
       $("nav").show();
       $(".portada").css("height","90vh");
       $(".cerrar-menu").show();
       $(".btn-menu").hide();
    })
    $(".cerrar-menu").click(function(){
        $(".portada").css("height","100vh");
        $(".btn-menu").show();
        $(".cerrar-menu").hide();
        $("nav").hide();
    })
})